"""SecondStep

Revision ID: 730cd40ce8ea
Revises: 7bfcf71e2d17
Create Date: 2022-05-06 16:52:52.354859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730cd40ce8ea'
down_revision = '7bfcf71e2d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.add_column('micro_posts', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'micro_posts', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'micro_posts', type_='foreignkey')
    op.drop_column('micro_posts', 'user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
